"""added time column

Revision ID: 1a910e372200
Revises: fc12a22211b0
Create Date: 2024-02-25 10:46:12.632533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a910e372200'
down_revision = 'fc12a22211b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('to_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')

    # ### end Alembic commands ###
