"""added new  time column

Revision ID: 45a49c554cd0
Revises: 0f8957b92b55
Create Date: 2024-02-25 11:36:25.657287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a49c554cd0'
down_revision = '0f8957b92b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_from_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('abs_to_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('abs_to_time')
        batch_op.drop_column('abs_from_time')

    # ### end Alembic commands ###
