"""added total_price column to cart

Revision ID: b5e3483da9e5
Revises: c73e9f2d071c
Create Date: 2024-03-05 18:01:54.087262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e3483da9e5'
down_revision = 'c73e9f2d071c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
