"""created table orderId

Revision ID: d9b1bffcdcc9
Revises: f9424f7b6feb
Create Date: 2024-03-10 16:40:25.106923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b1bffcdcc9'
down_revision = 'f9424f7b6feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderId',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderId')
    # ### end Alembic commands ###
